### ISSUE TITLE
double code report printing

### ISSUE THREAD

**Issue by mrsminiberger** [wliu-levansoft/media-coding#26]
I'm not sure how to describe this... I changed the Field name for subject_spokesperson to "Smokesperson" It was a joke for the coders... and updated the description for setting_outdoors... When I view the double code report in the web browser, everything looks fine, but when I then PRINT that report, these two fields are blank for the secondary coder.

**Comment by dannyl07** [comment]
Can you send me the URL for the double codes report please?

**Comment by mrsminiberger** [comment]
Also- logo looks like it wasn't initialized with -9997? 
![image](https://cloud.githubusercontent.com/assets/7119634/2820729/ae4df39a-cefd-11e3-9f7e-4850ac1ee22b.png)

**Comment by mrsminiberger** [comment]
https://reeldb.dartmouth.edu/Media-coding/review_double_coded_report/47/126

**Comment by dannyl07** [comment]
As for the empty field, I'm guess it's because the web layout is not optimized for printing, and one of the header/footer/left nav is covering up the line.  I'm fixing that now.

**Comment by dannyl07** [comment]
As for the uninitialized field.   The review was coded on 4/21, and the "logo" field was created on 4/23.  So there was not value stored in the database...therefore it is returned as blank or NULL value.  Would you like me to return -9997 if the answer_type is boolean or options and I can't find a valid value from the database?

**Comment by dannyl07** [comment]
I just released a new style sheet where the print view is optimized so the header/footer/left nav will not get in the way anymore.

Also, I went ahead and initialized the empty value as -9997 if it doesn't exist in the database.  This would have been an issue in the future if we add any additional fields without having the re-code all reviews again in order to pick up the new field.
